# Site settings
title: Pravo na informiranje
short_title: Pravo na informiranje
description: |
  Pristup informacijama temeljno je demokratsko načelo i pravo svih građana u suvremenim 
  demokracijama, koje omogućuje razvoj transparentne i otvorene javne vlasti, jača 
  odgovornost javnog sektora, potiče korisnički orijentirano djelovanje javne uprave, 
  suzbija korupciju i povećava legitimitet institucija i povjerenje građana u vlast.
baseurl: ""
url: "http://publikacije.codeforcroatia.org" # the base hostname & protocol for your site
github_username:  codeforcroatia
github_repo:  ppi-prirucnik
paypal: 
contact: http://diskurs.open.hr/
logo: povjerenik-za-informiranje.png
footer_logo: povjerenik-za-informiranje-footer.png

gems:
  - jekyll-redirect-from

devs:
  -
      name: Sam Smith
      github: smth
  -
      name: Rufus Pollock
      github: rgrp
  -
      name: Paul Walsh
      github: pwalsh
  -
      name: Miroslav Schlossberg
      github: schlos

contributors:
  -
      name: Anamarija Musa
      link: http://www.pristupinfo.hr/
  -
      name: Ina Volmut
      link: http://www.pristupinfo.hr/
  -
      name: Lucija Jadrijević
      link: http://www.pristupinfo.hr/
  -
      name: Dubravka Bevandić
      link: http://www.pristupinfo.hr/

supporters:
  -
    name: British Embassy Zagreb
    logo: british-embassy-zag.png
    footer_logo: british-embassy-zag-footer.png
    url: https://www.gov.uk/government/world/organisations/british-embassy-zagreb
  -
    name: Code for Croatia
    logo: codeforcroatia.png
    footer_logo: codeforcroatia-footer.png
    url: http://codeforcroatia.org/

developers:
  -
    name: Code for Croatia
    logo: codeforcroatia.png
    footer_logo: codeforcroatia-footer.png
    url: http://codeforcroatia.org/

publisher:
  -
    name: Povjerenik za informiranje
    logo: povjerenik-za-informiranje.png
    footer_logo: povjerenik-za-informiranje-footer.png
    url: http://www.pristupinfo.hr

googleanalytics: UA-8271754-XXX
google_verification: XXXXXXXXX

# Build settings
markdown: kramdown

permalink: pretty

languages:
  -
    - de
    - Deutsch
  -
    - el
    - Ελληνικά
  -
    - en
    - English
  -
    - es
    - Español/Castellano
  -
    - fr
    - Français
  -
    - he
    - עברית
  -
    - hr
    - hrvatski
  -
    - id
    - Bahasa
  -
    - is
    - Íslenska
  -
    - it
    - Italiano
  -
    - ja
    - 日本語
  -
    - ko
    - 한국어
  -
    - lt
    - Lietuvių
  -
    - lv
    - Latviešu
  -
    - nl_BE
    - Nederlands (Belgisch)
  -
    - pt_BR
    - Português Brasileiro
  -
    - ro
    - Română
  -
    - ru
    - Pyccĸий
  -
    - zh_CN
    - 中国语文
  -
    - zh_TW
    - 繁體中文

toc:
  - vodic
    - predgovor
    - pravo-na-pristup-informacijama
    - proaktivna-objava-informacija
    - ostvarivanje-prava-na-pristup-informacijama
    - odlucivanje-o-zahtjevu-za-pristup-informacijama
    - zastita-prava-na-pristup-informacijama
    - pristup-informacijama-za-novinare
    - korak-po-korak
    - ponovna-uporaba-informacija
    - savjetovanja-s-javnoscu
    - glossary
    - appendices
  - smjernice
    - predgovor
    - obveze-tijela-javne-vlasti
    - sluzbenik-za-informiranje
    - propisi
    - pojmovi
    - koraci-u-postupanju
    - rjesavanje-zahtjeva
    - zalidbeni-postupak
    - upravni-spor
    - ponovna-uporaba-informacija
    - ostvarivanje-ponovne-uporabe
    - uskrata-ponovne-uporabe
    - uvjeti-za-ponovnu-uporabu
    - naplata-troskova
    - proaktivna-objava-informacija
    - dostava-dokumenata-u-sredisnji-katalog
    - provedba-savjetovanja
    - javnost-rada
    - izvjesce-o-provedbi-zakona
    - rjecnik
    - prilozi
  - resources
  - credits

meta:
  resources:
    label: resources
    output: true
    has_translation: false
    title: Detaljnije o otvorenim podacima
    filters:
      - Topic
      - Language
      - Region
      - MediaType
  value-stories:
    label: value-stories
    output: true
    has_translation: true
    title: Open Data Value Stories
    languages:
      - hr
  glossary:
    label: glossary
    output: true
    has_translation: true
    translate_link: true
    title: Open Data Glossary
    languages:
      - hr
  vodic:
    label: vodic
    output: true
    has_translation: true
    translate_link: true
    title: Priručnik
    languages:
      - hr
    toc:
      entry_point: 'predgovor'
      order:
        - predgovor
        - pravo-na-pristup-informacijama
        - proaktivna-objava-informacija
        - ostvarivanje-prava-na-pristup-informacijama
        - odlucivanje-o-zahtjevu-za-pristup-informacijama
        - zastita-prava-na-pristup-informacijama
        - pristup-informacijama-za-novinare
        - korak-po-korak
        - ponovna-uporaba-informacija
        - savjetovanja-s-javnoscu
        - glossary
        - appendices
      chapters:
        - title: 'Predgovor'
          slug: 'predgovor'
          sections:
            - title: 'Ciljana publika'
              slug: 'ciljana-publika'
            - title: 'Zasluge i autorska prava'
              slug: 'zasluge-i-autorska-prava'
        - title: 'Pravo na pristup informacijama'
          slug: 'pravo-na-pristup-informacijama'
        - title: 'Proaktivna objava informacija'
          slug: 'proaktivna-objava-informacija'
        - title: 'Ostvarivanje prava na pristup informacijama'
          slug: 'ostvarivanje-prava-na-pristup-informacijama'
        - title: "Odlučivanje o zahtjevu"
          slug: 'odlucivanje-o-zahtjevu-za-pristup-informacijama'
        - title: "Zaštita prava na pristup informacijama"
          slug: 'zastita-prava-na-pristup-informacijama'
        - title: "Pristup informacijama za novinare"
          slug: 'pristup-informacijama-za-novinare'
        - title: "Korak po korak"
          slug: 'korak-po-korak'
        - title: "Ponovna uporaba informacija"
          slug: 'ponovna-uporaba-informacija'
        - title: "Savjetovanja s javnošću"
          slug: 'savjetovanja-s-javnoscu'
        - title: 'Appendices'
          slug: 'appendices'
  smjernice:
    label: smjernice
    output: true
    has_translation: true
    translate_link: true
    title: Smjernice
    languages:
      - hr
    toc:
      entry_point: 'predgovor'
      order:
        - predgovor
        - obveze-tijela-javne-vlasti
        - sluzbenik-za-informiranje
        - propisi
        - pojmovi
        - koraci-u-postupanju
        - rjesavanje-zahtjeva
        - zalidbeni-postupak
        - upravni-spor
        - ponovna-uporaba-informacija
        - ostvarivanje-ponovne-uporabe
        - uskrata-ponovne-uporabe
        - uvjeti-za-ponovnu-uporabu
        - naplata-troskova
        - proaktivna-objava-informacija
        - dostava-dokumenata-u-sredisnji-katalog
        - provedba-savjetovanja
        - javnost-rada
        - izvjesce-o-provedbi-zakona
        - rjecnik
        - prilozi
      chapters:
        - title: 'Predgovor'
          slug: 'predgovor'
          sections:
            - title: 'Ciljana publika'
              slug: 'ciljana-publika'
            - title: 'Zasluge i autorska prava'
              slug: 'zasluge-i-autorska-prava'
        - title: 'Obveze tijela javne vlasti'
          slug: 'obveze-tijela-javne-vlasti'
        - title: 'Službenik za informiranje'
          slug: 'sluzbenik-za-informiranje'
        - title: 'Propisi'
          slug: 'propisi'
        - title: "Temeljni pojmovi"
          slug: 'pojmovi'
        - title: "Prethodni koraci u postupanju"
          slug: 'koraci-u-postupanju'
        - title: "Rješavanje zahtjeva"
          slug: 'rjesavanje-zahtjeva'
        - title: "Žalidbeni postupak"
          slug: 'zalidbeni-postupak'
        - title: "Upravni spor"
          slug: 'upravni-spor'
        - title: "Ponovna uporaba informacija"
          slug: 'ponovna-uporaba-informacija'
        - title: "Ostvarivanje ponovne uporabe"
          slug: 'ostvarivanje-ponovne-uporabe'
        - title: "Uskrata ponovne uporabe informacija"
          slug: 'uskrata-ponovne-uporabe'
        - title: "Uvjeti za ponovnu uporabu informacija"
          slug: 'uvjeti-za-ponovnu-uporabu'
        - title: "Naplata troškova"
          slug: 'naplata-troskova'
        - title: "Proaktivna objava informacija"
          slug: 'proaktivna-objava-informacija'
        - title: "Dostava dokumenata u Središnji katalog"
          slug: 'dostava-dokumenata-u-sredisnji-katalog'
        - title: "Provedba savjetovanja s javnošću"
          slug: 'provedba-savjetovanja'
        - title: "Osiguravanje javnosti tijela javne vlasti"
          slug: 'javnost-rada'
        - title: "Izvješće o provedbi Zakona"
          slug: 'izvjesce-o-provedbi-zakona'
        - title: 'Prilozi'
          slug: 'prilozi'
  contribute:
    label: contribute
    output: true
    title: Contribute
    has_translation: false
    toc:
      chapters:
        - title: 'Contributing To The Handbook'
        - title: 'Adding A Page'
          slug: 'adding'
        - title: 'Editing A Page'
          slug: 'editing'
        - title: 'Adding A Term To The Glossary'
          slug: 'add-term'
        - title: 'Adding A Resource To The Library'
          slug: 'add-resource'
        - title: 'Translating The Guide'
          slug: 'translate-guide'
        - title: 'Translating The Glossary'
          slug: 'translate-glossary'
        - title: 'Markdown Examples'
          slug: 'markdown-examples'

defaults:
  -
    scope: #this should be removed once more specific paths are defined
      path: ""
    values:
      lang: hr
      layout: page
  -
    scope:
      path: "vodic"
    values:
      lang: hr
      layout: page
      edit: true
  -
    scope:
      path: "smjernice"
    values:
      lang: hr
      layout: page
      edit: true
  -
    scope:
      path: "contribute"
    values:
      lang: hr
      section: contribute
      layout: docs
      edit: true
  -
    scope:
      section: "terms"
    values:
      layout: page
      edit: true

related_projects:
  -
      name: ImamoPravoZnati.org
      link: https://imamopravoznati.org/
  -
      name: OpenGovernmentData.org
      link: http://opengovernmentdata.org/
  -
      name: The DataHub
      link: http://datahub.io/
  -
      name: DataPortals.org
      link: http://dataportals.org/
  -
      name: OpenSpending.org
      link: http://openspending.org/
  -
      name: SchoolOfData.org
      link: http://schoolofdata.org/
  -
      name: OpenDefinition.org
      link: http://opendefinition.org/
  -
      name: Introducing Open Data
      link: http://okfn.org/opendata/
